[all:vars]
ansible_user=sothea-phea
ansible_python_interpreter=/usr/bin/python3
; for first ssh, no need to answer yes no 
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[nfs-servers]
node1 ansible_host=34.97.125.100 ansible_connection=local 

[nfs-clients]
node2 ansible_host=34.126.142.195  
node3 ansible_host=35.247.177.199


[all:children]
nfs-servers
nfs-clients

; ansible -i inventory.ini -m ping node1 
; ansible -i inventory.ini -m ping all 
; ansible -i inventory.ini -m command -a "uptime" all 
; ansible -i inventory.ini -m apt -a "name=nginx state=present" node2 -b